GET http://127.0.0.1:8103/api/v1/test
api-key: b480eab3-5544-4a6b-ae34-b5e7e93ead60

###
#POST http://127.0.0.1:8103/api/v1/verifica-clasificacion
POST https://com-icg-mundial-api-clasificacion-587011279416.us-central1.run.app/api/v1/verifica-clasificacion/
api-key: b480eab3-5544-4a6b-ae34-b5e7e93ead60
Content-Type: application/json

{
  "mundial_id": 1, 
  "grupo": "Grupo B", 
  "confederacion_id": 5, 
  "fase_id": 1, 
  "paises": [
    {"_id": "68bb9703033a4535ed96cd30", "id": 152, "nombre": "Papúa Nueva Guinea", "siglas": "PNG", "iso": "PG", "rankin": 1, "puntos": 2, "jj": 2, "jg": 0, "je": 2, "jp": 0, "gf": 7, "gc": 7, "lat": -6, "lng": 147, "federacion": "FEDERACIÓN DE FÚTBOL DE PAPÚA NUEVA GUINEA", "confederacion_id": 5, "valor": 700, "p_ofensiva": 100, "p_defensiva": 100, "p_posesion": 50, "tactica_id": 0, "poder": 135, "efectividad_gol": 35.0, "promedio_gol": 3.5, "user_id": 0, "estadisticas": None, "estado": "disponible"}, 
    {"_id": "68bb9703033a4535ed96cd3e", "id": 166, "nombre": "Samoa", "siglas": "SAM", "iso": "WS", "rankin": 2, "puntos": 2, "jj": 2, "jg": 0, "je": 2, "jp": 0, "gf": 7, "gc": 7, "lat": -13.58, "lng": -172.33, "federacion": "FEDERACIÓN SAMOANA DE FÚTBOL", "confederacion_id": 5, "valor": 700, "p_ofensiva": 100, "p_defensiva": 100, "p_posesion": 50, "tactica_id": 0, "poder": 135, "efectividad_gol": 35.0, "promedio_gol": 3.5, "user_id": 0, "estadisticas": None, "estado": "disponible"}
    ]
}



{
    "mundial_id": 1,
    "grupo": "Grupo A",
    "confederacion_id": 6,
    "fase_id": 1,
    "paises": [
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cd1e"
        },
        "id": 134,
        "nombre": "Mongolia",
        "siglas": "MNG",
        "iso": "MN",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": 46,
        "lng": 105,
        "federacion": "FEDERACIÓN MONGOLA DE FÚTBOL",
        "confederacion_id": 6,
        "valor": 600,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      },
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cd59"
        },
        "id": 193,
        "nombre": "Timor Oriental",
        "siglas": "TLS",
        "iso": "TL",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": -8.83,
        "lng": 125.92,
        "federacion": "FEDERACIÓN TIMORENSE DE FÚTBOL",
        "confederacion_id": 6,
        "valor": 600,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      }
    ]
}



{
  "mundial_id": 1, 
  "grupo": "Grupo B", 
  "confederacion_id": 5, 
  "fase_id": 1, 
  "paises": [
    {"_id": "68bb9703033a4535ed96cd30", "id": 152, "nombre": "Papúa Nueva Guinea", "siglas": "PNG", "iso": "PG", "rankin": 1, "puntos": 2, "jj": 2, "jg": 0, "je": 2, "jp": 0, "gf": 7, "gc": 7, "lat": -6, "lng": 147, "federacion": "FEDERACIÓN DE FÚTBOL DE PAPÚA NUEVA GUINEA", "confederacion_id": 5, "valor": 700, "p_ofensiva": 100, "p_defensiva": 100, "p_posesion": 50, "tactica_id": 0, "poder": 135, "efectividad_gol": 35.0, "promedio_gol": 3.5, "user_id": 0, "estadisticas": None, "estado": "disponible"}, 
    {"_id": "68bb9703033a4535ed96cd3e", "id": 166, "nombre": "Samoa", "siglas": "SAM", "iso": "WS", "rankin": 2, "puntos": 2, "jj": 2, "jg": 0, "je": 2, "jp": 0, "gf": 7, "gc": 7, "lat": -13.58, "lng": -172.33, "federacion": "FEDERACIÓN SAMOANA DE FÚTBOL", "confederacion_id": 5, "valor": 700, "p_ofensiva": 100, "p_defensiva": 100, "p_posesion": 50, "tactica_id": 0, "poder": 135, "efectividad_gol": 35.0, "promedio_gol": 3.5, "user_id": 0, "estadisticas": None, "estado": "disponible"}
    ]
}