GET http://127.0.0.1:8103/test
api-key: b480eab3-5544-4a6b-ae34-b5e7e93ead60

###
POST http://127.0.0.1:8103/api/v1/verifica-clasificacion
api-key: b480eab3-5544-4a6b-ae34-b5e7e93ead60
Content-Type: application/json

{
    "mundial_id": 1,
    "grupo": "Grupo A",
    "confederacion_id": 6,
    "fase_id": 1,
    "paises": [
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cd1e"
        },
        "id": 134,
        "nombre": "Mongolia",
        "siglas": "MNG",
        "iso": "MN",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": 46,
        "lng": 105,
        "federacion": "FEDERACIÓN MONGOLA DE FÚTBOL",
        "confederacion_id": 6,
        "valor": 600,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      },
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cd59"
        },
        "id": 193,
        "nombre": "Timor Oriental",
        "siglas": "TLS",
        "iso": "TL",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": -8.83,
        "lng": 125.92,
        "federacion": "FEDERACIÓN TIMORENSE DE FÚTBOL",
        "confederacion_id": 6,
        "valor": 600,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      }
    ]
}
