GET http://127.0.0.1:8103/test
api-key: b480eab3-5544-4a6b-ae34-b5e7e93ead60

###
POST http://127.0.0.1:8103/api/v1/verifica-clasificacion
api-key: b480eab3-5544-4a6b-ae34-b5e7e93ead60
Content-Type: application/json

{
    "grupo": "Grupo A",
    "confederacion_id": 1,
    "fase_id": 1,
    "paises": [
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cd0f"
        },
        "id": 119,
        "nombre": "Lituania",
        "siglas": "LTU",
        "iso": "LT",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": 56,
        "lng": 24,
        "federacion": "FEDERACIÓN LITUANA DE FÚTBOL",
        "confederacion_id": 1,
        "valor": 1000,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      },
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cd51"
        },
        "id": 185,
        "nombre": "Suecia",
        "siglas": "SWE",
        "iso": "SE",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": 62,
        "lng": 15,
        "federacion": "FEDERACIÓN SUECA DE FÚTBOL",
        "confederacion_id": 1,
        "valor": 1000,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      },
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96ccf2"
        },
        "id": 90,
        "nombre": "Inglaterra",
        "siglas": "ENG",
        "iso": "GB-ENG",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": 54,
        "lng": -2,
        "federacion": "FEDERACIÓN INGLESA DE FÚTBOL",
        "confederacion_id": 1,
        "valor": 1000,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      },
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cc9b"
        },
        "id": 3,
        "nombre": "Alemania",
        "siglas": "GER",
        "iso": "DE",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": 51,
        "lng": 9,
        "federacion": "FEDERACIÓN ALEMANA DE FÚTBOL",
        "confederacion_id": 1,
        "valor": 1000,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      },
      {
        "_id": {
          "$oid": "68bb9703033a4535ed96cd39"
        },
        "id": 161,
        "nombre": "República Checa",
        "siglas": "CZE",
        "iso": "CZ",
        "rankin": 0,
        "puntos": 0,
        "jj": 0,
        "jg": 0,
        "je": 0,
        "jp": 0,
        "gf": 0,
        "gc": 0,
        "lat": 49.75,
        "lng": 15.5,
        "federacion": "FEDERACIÓN CHECA DE FÚTBOL",
        "confederacion_id": 1,
        "valor": 1000,
        "p_ofensiva": 100,
        "p_defensiva": 100,
        "p_posesion": 50,
        "tactica_id": 0,
        "poder": 0,
        "efectividad_gol": 0,
        "promedio_gol": 0,
        "user_id": 0,
        "estadisticas": null,
        "estado": "disponible"
      }
    ]
}
